---
title: "West Lesson"
author: "Tanner Mierow"
date: "`r Sys.Date()`"
output: html_document
---
# Load packages
```{r}
library(AICcmodavg)
library(MuMIn)
```

# Make Model
```{r}
SD_banding_data <- read_csv("SD_banding_data.csv")
banding <- SD_banding_data
banding_na<-na.omit(banding)
model <- glm(fat~species+mass+tarsus, data = banding_na, family=gaussian)

band_model<- glm(fat~species+mass+tarsus, data = banding_na, family=gaussian,
                 na.action = na.fail)
                 
AICc_band_models <- dredge( #construct all possible models
  band_model,    #use band model as a reference
  rank = "AICc", #use AICc scores to compare
  fixed = "species")
```
# Check model output
```{r}
summary(model)
```
# Get model list
```{r}
model_list <- get.models(AICc_band_models, #retrieve models from dredged data
                              subset = TRUE)
model_list[1]
```
# Run ANOVA 
```{r}
anova(model)
```
# Get AIC scores
```{r}
AIC(model)
AICc(model)
```
# Get all model combos
```{r}
AICc_band_models <- dredge(model, rank = "AICc", fixed = "species")
```
# Make model name list
```{r}
model_name_list<-NULL

for (i in 1:10){
  model_name_list = c(model_name_list, as.character(model_list[[i]][['formula']]))
}

model_name_listb <- model_name_list[seq(3, length(model_name_list), 3)]
# Make AIC table 
modavg_table<-aictab(model_list,
                     modnames = model_name_list,
                     second.ord = TRUE,
                     sort = TRUE)
modavg_table
```
