---
title: "Assignment 3"
author: "Tanner Mierow"
date: "2022-09-22"
output: html_document
---
Question 1: 

Candidate Choice, Absentee Mail, Early Voting, Election Day, Total Votes
TODD RUSS, 7,021, 8,194, 135,216, 150,431
CLARK JOLLEY, 7,012, 5,835, 107,714, 120,561

"find --> \s{3,}
replace --> , "

Question 2: 

Emily Adamic    (ema3896@utulsa.edu)
Emily Bierbaum  (elb0588@utulsa.edu)
Laci Cartmell   (ljc454@utulsa.edu)
Elise Delaporte    (eld0070@utulsa.edu)
Rebekah Hansen  (reh9623@utulsa.edu)
Madison Herrboldt   (mah1626@utulsa.edu)
Cari Lewis  (cdl5261@utulsa.edu)
Tanner Mierow   (ttm5619@utulsa.edu)
Daniel Naranjo  (dsn8679@utulsa.edu)
Caleb Paslay   (cap1050@utulsa.edu)
Olivia Pletcher (omp9336@utulsa.edu)
Amy West    (acw1471@utulsa.edu)

Find: (\w+), (\w+) (\w{1}).
Replace: \2 \1

Find: (\w+), (\w+)
Replace: \2 \1


Find: (\w{6,}@\w{6}.\w{3})
Replace:(\1)

Question 3: 

Banded sculpin, 5
Redspot chub, 5
Northern hog sucker, 6
Creek chub, 8
Stippled darter, 9
Smallmouth bass, 10
Logperch, 13
Slender madtom, 14

Find: , \w{3,} \w{3,}
Replace: "nothing"

Question 4: 

Banded sculpin, C_carolinae, 5
Redspot chub, N_asper, 5
Northern h_sucker, H_nigricans, 6
Creek chub, S_atromaculatus, 8
Stippled darter, E_punctulatum, 9
Smallmouth bass, M_dolomieu, 10
Logperch, P_caprodes, 13
Slender madtom, N_exilis, 14

Find: (\w)\w+ (\w{3,})
Replace: \1_\2

Question 5: 

Banded sculpin, C_car., 5
Redspot chub, N_asp., 5
Northern h_suc., H_nig., 6
Creek chub, S_atr., 8
Stippled darter, E_pun., 9
Smallmouth bass, M_dol., 10
Logperch, P_cap., 13
Slender madtom, N_exi., 14

Find: (\w)\w+ (\w{3})\w+
Replace: \1_\2.

Question 6: 

The command I used was Grep and I used it to create the headers for the Ladona fulva (dragonfly) proteins
Headers:
>KAG8212618.1 hypothetical protein J437_LFUL013901 [Ladona fulva]
>KAG8212619.1 hypothetical protein J437_LFUL013902 [Ladona fulva]
>KAG8212620.1 hypothetical protein J437_LFUL013903 [Ladona fulva]
>KAG8212621.1 hypothetical protein J437_LFUL013904 [Ladona fulva]
>KAG8212622.1 hypothetical protein J437_LFUL013905 [Ladona fulva]
>KAG8212623.1 hypothetical protein J437_LFUL013906 [Ladona fulva]
>KAG8212624.1 hypothetical protein J437_LFUL013907 [Ladona fulva]
>KAG8212625.1 hypothetical protein J437_LFUL013908, partial [Ladona fulva]
>KAG8212626.1 hypothetical protein J437_LFUL013909, partial [Ladona fulva]
>KAG8212627.1 hypothetical protein J437_LFUL013910 [Ladona fulva]

Question 7: 

The command I used was grep to find the headers and sed to find and add in the sequences
Headers:
>KAG8212618.1 hypothetical protein J437_LFUL013901 [Ladona fulva]
MERLQVENASEWGRRERLESDKQALERENRRLRTELRDLLERIERMDSGVGSVETREKSKDSSSQATRHGHSINSPPFST
ASSASSSSSTSSAAATAAAQAEMIKQLQQELAEKTKELEELKIAHSKLKAVVRERSTEAAHGARRAEQYEAEVKRLRVRV
DELRKELAAAEEEVDAATNNIRKLKRTNEDLQEQVENMQVQIEHLQSRRDSLLETPMPDLSSSRKEITLPGPMEDHGCDC
GMYPHSCCQSIVDHREDADTTDLAVPEGTEGEDLLADGLVNRGNKFSFGVFVLLKLIHQQQHGDPSGLVGGRGLHILALP
FDPKTTLHENVKYPQVDDLTELVTLLHLDRLLQAPYHLHLYLVEIMDPSGLWTVPIPCPGANPVPRIACPGRNCPPSGYR
PSIPVPGALIPSGARCPGRPTPPGPLN
>KAG8212619.1 hypothetical protein J437_LFUL013902 [Ladona fulva]
MGQSQSQSSVGDGCEDCYPGGYAGGGGGHGPWQAGYGQGGRLPGSAGVDGVGAGRGTGLGPGGGRGYGPGSPGYGRPGAP
GFDDTSGLSQGQQMRPGSLAQRPVTTGVEGPGYMGIPGVPPGRGIGGVGGYGTDGTGTAGGPGYRRPTGVTGIQPGTPGY
VGPTGTGYGHQPGAPGYRGPGVAGHGIPTAGGGVTRPGHGGAYPGRPGYVPSTGTQHGGYGQVPSGTGGVTRPHGSSGHL
APGEGAGVGPGGMIQPGAGYPTGSGQQLPDGVPSAHGGQHLGPGMIQRPVGTHDYGAPGYGTHIGVGDGRHPGGGRMPIG
GVGGRVPSGFGGQTVPQGGQMVPSGHGVPGHGLYGPGTGRGTTGYGTYPGAVPGRGIQDGRLHHVPSGGGAPVGVPGHLG
VPGGHAGIPGHTGIQGVHPSGSGVGIPGGQVGVPGHAGVQGAHVPTGYIPGGSGVHGVPGQVGVPGGYHRPGVDGVGAGY
PGVHPGTHGVPQGYDRYPSGVTGHGLTAPGGAGQFRGPGGVGLPGHLAPEGIRAPGTGIDGRYPDGGQLRPGQAILGTGL
APGHGIGTVQRPDGSLVGVDQYGRPGVTGYPGGQRPGYGIDGQYGPGYYDGQAYPLSRPGTGVGGRVPVGGGPDGGESQA
QSSVTQDDKEIKAGASSQGRLGDGKAQAQVSGSYSGTGSFSAQAQTSDNGRSAQSQVTGNKDGGSSSAQGNGGKGQSQAQ
VQLSSANGATKAEAQSGGWQYGSNTQVQAGENGGMADAQSSGPGTTSSQAQVGFKPYRANGNVQRTPFRGGGTASAQSSS
YSGQSQSQVQGAYRYGVSFTGAAQAGSGTRGSRGIGNNRNGTRFERDDHAALSPDTFKLKPLNNFGDLSTPSQSEGQDGR
KVPESQVNQMNGNLGGRHQGGMDNSGIHSSNAGGIHQNGHGSNGHVSNVHGSNAHGSNGHRPNGHGSSAHGSNGHGANEN
SHFNGMHVPPSRGQINGQRGQQTHNGHQQYNGNSHGIQSPHSNGHQQVHSLNQNVHAPLQGQETSTEMAGHKTSQHDHSV
NGNRQPENEYPRFDNGDSRSQQHGGMQGVDYSRDISQTGGKPAVFKTESPRQSQAVFISPMGNEDVHITQAADGGGIPAH
PVYQPGQVVPGSSGYVIPEGFRGRVITDSRSIAGDETIAVASPNNGNSQSQTVVLTPGSGKVNYTRIVRPPPGQPVEPAF
QDYGQNQNVDEESEMAMRGDTHNFGSNVYRRGDQHVYVKNKMHTRSGGESSSSNQKVDDYDEEDEDEVEEEEEEDEEEVQ
ASSTPLPANTYVSVTNSVSGQLNPQGGGGRLYTNGNVGNRGSEGGKFAHTYYTKSSTCGYFTFSCNVVFGSNGRAKICKP
RPPTNPDGSPCCC
>KAG8212620.1 hypothetical protein J437_LFUL013903 [Ladona fulva]
MTSNSRRVAIISLRDTMSSWRRLHPLQVYDILLELLLALELHEHLILQEYIQLGHVLPELQHVQAPQPVLPVYRHVLQEL
LGGLERQPEHLLQTARGEVFRLVFLFQEQHRDMFHNLLYHALFRDHIIHVQEHHVRRVPSAHLEVPFVRQTLMGLFLQHL
Q
>KAG8212621.1 hypothetical protein J437_LFUL013904 [Ladona fulva]
MPPISNADVLRNHAFRQVFESCQGLGAGHHAQMERRQVVADQIQLDNLLPVVSFLLGQLLRPPPVPDAQKIRVAALRHQF
R
>KAG8212622.1 hypothetical protein J437_LFUL013905 [Ladona fulva]
MFHQYPVRVDVDLEARTAIVSPPDNIPGLGKSRTFYDYNTRVIAYKDYRSKQCHLERMSDEEKLPGVEEDSTKQNEEGPE
GSEAREAERRLHRQMGLLGPTQHNRNRQKRAPQSKQLNGMRRKPKTLYVTETVLSKYEVLRLAGRRISHFCRGFPATLLV
QRPPNPTPKLQSPARIPWLSENELPGEGSTESEEHRLLLEAALVKARLAELELQTLDSSDEESPQDHGKTNKGTFLRALS
YLHVPQVALLFQSGLPSLSGEKAYETSMPTLEPRVFLPAPQLTENNPEVISDFSQKESR
>KAG8212623.1 hypothetical protein J437_LFUL013906 [Ladona fulva]
MQVFITPLHLCIPESSPERSVSEAEHRRSAAEANIASETPPGSNHTSTFHTNGHSSHPFSLESAWTAVATASVPRKASHR
KDGEDNGGEECPEELYNLTKLAEVSLAAAAGHVFVPQPIPSSVREESSRDGEEDDDGSRDDDEDYNFSQRSNSPRQRNSA
EYHGCPECGKRYSTSSNLARHRQTHRSLADKKARRCPHCDKVYVSMPAFSMHVRTHNQGCKCPFCGKCFSRPWLLQGHIR
THTGEKPFRCSVCDKAFADKSNLRAHVQTHSNEKPFVCGRCGKAFALKSYLYKHEESSCMRIHHGGSVKTHDDKDPKISP
GKKNSRAGQFGQGEQGRKVEEVTTTTVTVIHSSEFGGCVVSDAGSRSPQSVFPMNGRSDSGNSSPVSPVHFQDHVHPQQE
QRDQQHLQHHHGAHNPHNLYAGRLHMMSAGIAV
>KAG8212624.1 hypothetical protein J437_LFUL013907 [Ladona fulva]
MAVVDSHVVELREIFQDFSTKISRHVSEKSSLNLEELQKLLDELIVFTRNVPNDAVIYPDYDIILTSLGSIVSVHKLDLL
VKSCQFMCYLVGLHNVKLRKEHIERMFNLCLQGLRVINSSTDILHVFNAMETLLQADQNDTLEKFNILTNLASPKNGILI
QMLSDKETSGPLLLAAVGCLELLLSPPSLSGYSDASVEKQIKMDEICETCMQTLISILGRGKPEDLDDLGYCKLIVAAMR
GIHHILAPAIRASETSKILTPSGRLGEVVGIITAFMGLGLNDRQGSIKYPVGPLKANMSSHIMPVVPQELEEGKDGYKGR
TTKVSDAAFD
>KAG8212625.1 hypothetical protein J437_LFUL013908, partial [Ladona fulva]
MPQRSIHPALNSVRLEPDDPKLPSWQMTSDSDMSSSDVESVKVKDSEGRTAFSKVRQMSCSLLLCVIKVTQPSVLFAFWP
SLLPDGMPTGPGHLLPIPLKVGDQVTLATLMLHDPASKGRALAAMVLAALLTSWQRFLTEAECS
>KAG8212626.1 hypothetical protein J437_LFUL013909, partial [Ladona fulva]
VLSSIARNQELAPKLLLHSDFWPLLQTRLIIGPGNLHESVDISSLKYHWGKFWESLGLAIRRCVELKGEPVLTHSQAVAF
WQAFISGTSLVPLIQDMNNVSLRVVGCDVLATVGETVFGQIM
>KAG8212627.1 hypothetical protein J437_LFUL013910 [Ladona fulva]
MLLSGDHIAAVDADPTLLDRLITGDITWCYLNDPQSKRQSMVWKSLSSPWPKKFRADGSRGKVMLVVFFNCKEIVHYELV
PEGCTVNKELHVTIFKWLRKAVCWKRPDLWQQKFWVLHHDNAPIHRSLLVTQFLDKHDILTLPQPPYSTDLIPCEFFLFH
RFKSHLKGRRYTDSEAEQTAATRTLTEVAKTGL
>KAG8212628.1 hypothetical protein J437_LFUL013911 [Ladona fulva]
MRMSQFEQRSIVRFCVLLGKMFVQTFELIKQAYGDAALGQTAVYNWQSLKDNQRSGWPSTACNDEIIAQVRDIILADSRQ
TVADVAGLANISIGSCHAILHDD
>KAG8212629.1 hypothetical protein J437_LFUL013912 [Ladona fulva]
MDLHFLLDTADTLQSALESDASRGEVWVKASWALGNLTDAFILNKEEGLADAVPDGPLLELLETCASACQKLPKGGNSAD
RVRCNAVRAAGNIVRLIDFRGWDEMAGNMSLFSLGKRGKDAVEKIVFTLVDAATKSCDMKVRWNACYAISGLLKNSTLYD
NSCAYDDLVTKIVLTLCHLAKLVEKGDLVLLGEIIDPYLENTQSQMISRSHSLVPEKASFIGEAALCLAAFRKNDAASLT
RIEDECLSKLIKIFSPDNSKKFSGVYPF
>KAG8212630.1 hypothetical protein J437_LFUL013913 [Ladona fulva]
MEDENNDDLDEKGKPIVAKSAYDLQRLKLEKLMKNPEKPIPIPERPKGKNLPPTPDFVRNVMGSSAGAGSGEFHVYRHLR
RKEYARQKFIQEKGVKETLEEQYHRKIEMNRIEAEERTAKKRAKRLKKKQKSKKPKPSGDKQETKEAEDSSSDSKDEADD
>KAG8212631.1 hypothetical protein J437_LFUL013914 [Ladona fulva]
MADLEAVLADVSYLMAMEKSKCTPAARASKKIILPDPRVISLPNYAKNVAIYHWMPITVMRVHKL
>KAG8212632.1 hypothetical protein J437_LFUL017211, partial [Ladona fulva]
NGGWSPWSQWSECSARCGRGVQKRSRLCTHPAPLHGGLPCQGSATQKVDCTTMCPAVDGRWSGWSAWSTCGPDCRHHRRR
TCNSPAPANGGKYCQGRDHATANCSDGMCRLSDSTSSTSSSSSSPVSSGGSGGGNSGEFQPPFGIVYLPLKIISFVW
>KAG8212633.1 hypothetical protein J437_LFUL018167 [Ladona fulva]
MEYIHHVATEKIILPPKISPVFGKKTFSKAIVEPAQYVEDIELNSASPEESKEDESIEDFVRSVLRDRIHGTLPILQQRD
RRCSKLGNVAGGDWKSWTEL
>KAG8212634.1 hypothetical protein J437_LFUL018672 [Ladona fulva]
MIFCLIVQQSPVGGGSPLVGGGGAGPRDAHETGSTHDETSSSGNKEDEEDDDDMFVRLFVDENLDRMVPISKQPKEKIQA
IIDSCTRQFPEFAERARKRIRTYLKSCRRNKRSRDSNGVWDATRPTPAHLTSVQAEQILAQACENESQNAKRMRLGLEPV
SQPMPILPTDRTMDLYSIAPSLVDKKSDIVMSDCNAATVTTTATTPSSSSTSSSSAPSPPTLIATTSSIAITTASTGVGP
SPSPSPSSATPILPSSAITTTSSAHHPHHPHHPHLPIHASQAHLAHIAVTSTTSPAPLAISSSPTAVAAIPFNKTMGSLA
DAKASVPLTTAATLNGSVTAATGLASQPAPSTLYRPNFTQAFQRSTAVGGGVGSNGGPNPGAPVPSATGTYPGPLFPSSQ
FGPGGMIGNGTGPTDLSMKSKPLLSHKLNSAEMAAVKQLITGYRESAAFLLRSADELEQLLLQQQ


