---
title: "HerrboldtLesson"
author: "Tanner Mierow"
date: "`r Sys.Date()`"
output: html_document
---
# Load library
```{r}
library(readr)
library(ggplot2)
```
# Create data variable
```{r}
MAH_assignment_data <- read_csv("MAH_assignment_data.csv")

AssignmentData <- MAH_assignment_data
```
# Create GG plot with assignment data
```{r}
ggplot(AssignmentData,
       aes(x = Sample, y = Gene, fill = Expression)) +
geom_tile()
```
# Create heat map!
```{r}
ggplot(AssignmentData,
       aes(x = Sample, y = Gene, fill = Expression)) +
  geom_tile(colour = "black", linewidth = 0.5) +
  scale_fill_gradient(low = "white", high = "purple") +
  theme_grey(base_size = 12) +
  ggtitle(label = "Pheromone Gene Expression") +
  theme(axis.ticks = element_blank(),
        plot.background = element_blank(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        plot.title = element_text(face = "bold"),
        legend.title = element_text(face = "bold"),
        axis.title = element_text(face = "bold"))
```